apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
  labels:
    app.kubernetes.io/part-of: taskflow
data:
  POSTGRES_DB: "taskflow"
  POSTGRES_USER: "taskflow"
  POLL_INTERVAL_SECONDS: "10"
  API_URL: "http://taskflow.local"
