apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
  namespace: taskflow
  labels:
    app.kubernetes.io/part-of: taskflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: "taskflow-dev-password"
  DATABASE_URL: "postgresql+psycopg2://taskflow:taskflow-dev-password@db:5432/taskflow"

