apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: taskflow
  labels:
    app: db
    app.kubernetes.io/part-of: taskflow
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

